### PR TITLE
Eliminated instanceof and added tests

### PR DESCRIPTION
**Pull request by xogeny**
These commits eliminate the need for `instanceof` (which can be dangerous) and replaces it
with tagged unions.  This avoids some of the problems with `instanceof` while maintaining a 
high degree of type safety.

I've also put together several examples of `.toml` files and written Jest tests that parse them
and compare them with expected results.

### CODE REVIEW

**Comment by xogeny** [comment]
I'd merge this myself.  But according to GitHub, @xogeny doesn't have write access.

**Comment by sgarciac** [comment]
Hi Michael, I added mtiller to the list. xogeny is still listed as "Awaiting for response" in the collaborators list, I think you need to confirm it here: https://github.com/sgarciac/bombadil/invitations

**Comment by xogeny** [comment]
@sgarciac Doh!  You are right.  Completely my fault.  Should be merged now.  If you follow this project in CircleCI, it should give you notifications about whether the builds and tests succeed, BTW.

**Comment by sgarciac** [comment]
Great changes!

**Pull request merged**
